[package]
name = "adxl343"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_setters = "0.1.9"
embedded-hal = "1.0.0"
embedded-hal-mock = "0.11.1"
linux-embedded-hal = "0.4.1"
lsm6ds3tr = "0.2.2"
modular-bitfield = "0.13.1"




